<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-12-17 10:52

$extensionPath = t3lib_extMgm::extPath('newsdirsync');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_newsdirsync_hooks_tcemain' => $extensionClassesPath . 'Hooks/Tcemain.php',
	'tx_newsdirsync_synchronize_folder' => $extensionClassesPath . 'Synchronice/Folder.php',
);
?>